### ISSUE TITLE
write image to the record failed: AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by GabrielZZZ** [daohu527/cyber_record#55]
Hi @daohu527 ,

I have successfully used your recover tool to repair the file (after updating the cyber_record). Then I split the file to delete the original imaes. My idea is by transforming the image extracted and then writing it back to the record file to test Apollo. However, when I try to write image data back to the record file, it gives me error: AttributeError: 'NoneType' object has no attribute 'shape'
![image](https://user-images.githubusercontent.com/42797233/195124066-e30761cd-d2ee-4206-ba6b-bf8064e96dd3.png)

Moreover, I tried to write other images to an empty file, and this error is still encountered, but I have not encountered it before I updated the tool (I am using the same data as before). Is there anything conflict among these updates?
![image](https://user-images.githubusercontent.com/42797233/195124535-bcbc0483-3efb-4d79-bbf0-1b6826b0d768.png)

**Comment by daohu527** [comment]
In fact, I don't know your operation process, you can write down the operation steps in detail then we can find what's wrong

**Comment by GabrielZZZ** [comment]
Good idea, here are the steps I followed:

1. I update the cyber_record tool
2. Since the `cyber_record recover` command not work on my device (I am using Ubuntu 20.04, it shows "command not found"), I use the recover function inside my code and repaired the demo
3. I extracted the images,and it worked fine:
![image](https://user-images.githubusercontent.com/42797233/195233405-0db4c1bf-0f5c-4cc0-a735-8f0556218cfa.png)
![00001](https://user-images.githubusercontent.com/42797233/195233421-054b245b-bcd4-40b2-ba8f-e09bd1f026b9.jpg)

4. First, I tried to write these images to an empty record first, and here is the error:
![image](https://user-images.githubusercontent.com/42797233/195233238-9f94307a-5de9-4fbb-9459-8a08019f94a5.png)
6. Then I tried to write these images back to the original record file that has been splitted images, and here is the error:
![image](https://user-images.githubusercontent.com/42797233/195233675-d7e7d8e4-40ea-4ec4-baf7-df5b33d50abe.png)

HERE is the code of writing image back to record:
![image](https://user-images.githubusercontent.com/42797233/195233903-46556f3b-332c-4dd8-81ac-3f2e062129c1.png)

**Comment by daohu527** [comment]
I checked the code and it works well. Maybe your img path is error and I and check in `record_msg` now.

```python
def write_image():
  '''
  img_dir: image folder
  '''
  image_builder = ImageBuilder()
  write_file_name = "example_w.record.00002"
  img_dir = "../tests/"
  with Record(write_file_name, mode='w') as record:
    img_paths = sorted(os.listdir(img_dir))
    for img_path in img_paths:
      if img_path.endswith(".jpg"):
        file_path = img_dir + img_path
        print(file_path)

        pb_image = image_builder.build(file_path, encoding='rgb8')
        record.write('/apollo/sensor/camera/front_6mm/image',
                    pb_image,
                    int(time.time() * 1e9))
  print("Success write image!")
```

**Comment by GabrielZZZ** [comment]
I double-checked the img path. I added a print command of the `image_list` I used before writing to record, and program can read the images
![image](https://user-images.githubusercontent.com/42797233/195480723-49472619-91db-4577-947f-11b4f07e14f5.png)

**Comment by daohu527** [comment]
Pls use `Record(write_file_name, mode='w')` mode='a' is not support for now!

**Comment by daohu527** [comment]
so it depends on mode='a', and I will finish it in a few days

**Comment by GabrielZZZ** [comment]
Thanks a lot!
